---
title: "hw02-Lai-Wei"
output: github_document
---


```{r}
#install.packages("readr")
github <- "https://github.com/ucb-stat133/stat133-fall-2017/raw/master/"
file <- "data/nba2017-player-statistics.csv"
csv <- paste0(github, file)
download.file(url = csv, destfile = 'nba2017-player-statistics.csv')
```
```{r}
library(readr)
# vector of data types (for each column)
col_types <- c(
    'character', 'character', 'factor', 'character', 'double','integer', 'integer', 'integer', 'integer','integer', 'integer','integer', 'integer','integer', 'integer','integer', 'integer','integer', 'integer','integer', 'integer','integer', 'integer','integer'
)

df1 <- read.csv(
    'data/nba2017-player-statistics.csv',
    header = TRUE,
    colClasses = col_types,
    sep = ","
)

df2 <- read_csv(
  'data/nba2017-player-statistics.csv',
   col_types  = list(col_character(), col_character(), col_factor(c("C", "PF", "PG", "SF", "SG")), col_character(), col_double(), col_integer(), col_integer(),col_integer(),col_integer(),col_integer(),col_integer(),col_integer(),col_integer(),col_integer(),col_integer(),col_integer(),col_integer(),col_integer(),col_integer(),col_integer(),col_integer(),col_integer(),col_integer(),col_integer())
)

str(df2)

df1 <- data.frame(df1)
df2 <- data.frame(df2)

str(df2)
str(df1)

df1$Experience <- chartr("R", "0", df1$Experience)
df1<-transform(df1, Experience = as.integer(Experience))
df2$Experience <- chartr("R", "0", df2$Experience)
df2<-transform(df1, Experience = as.integer(Experience))

df1$Missed_FG <- df1$FGA - df1$FGM
df1$Missed_FT <- df1$FTA - df1$FTM
df1$PTS <-df1$Points3*3 + df1$Points2*2 + df1$FTM
df1$REB <-df1$OREB + df1$DREB
df1$MPG <- df1$MIN / df1$GP
df1$EFF <- (df1$PTS + df1$REB + df1$AST + df1$STL + df1$BLK - df1$Missed_FG - df1$Missed_FT - df1$TO) / df1$GP
summary(df1$EFF)

print (hist(df1$EFF),  main="Histogram of EFF", xlab="EFF")
str(df1[ c(1:10), c(1, 2, 5,30)])
df1[df1$EFF < 0,'Player']

cor_pts <-cor(df1$PTS, df1$EFF)
cor_reb<-cor(df1$REB, df1$EFF)
cor_ast<-cor(df1$AST, df1$EFF)
cor_stl<-cor(df1$STL, df1$EFF)
cor_blk<-cor(df1$BLK, df1$EFF)
cor_mfg<-cor(-df1$Missed_FG, df1$EFF)
cor_mft<-cor(-df1$Missed_FT, df1$EFF)
cor_to<-cor(-df1$TO, df1$EFF)

corre <- data.frame(
  category <- c('PTS', 'REB', 'AST', 'STL', 'BLK', 'MFG','MFT', 'TO'),
  influence <- c(cor_pts, cor_reb, cor_ast, cor_stl, cor_blk, cor_mfg, cor_mft, cor_to)
)
corre <- corre[order(-corre$influence),]
corre

barplot( corre$influence,  
  main = "Correlations between Player Stats and EFF", ylim=c(-1,1), names.arg = corre$category)

scatter.smooth(df1$EFF, df1$Salary)
lines(lowess(x = df1$EFF ,y= df1$Salary))
print (cor(df1$EFF, df1$Salary))
print ("The relationship between these  players is in positive linear relationship. ")

players2 <-data.frame(
  people <- c(df1[df1$MPG >= 20,'Player']),
  EFFiciency <-  c(df1[df1$MPG >= 20,'EFF']),
  Salary <-  c(df1[df1$MPG >= 20,'Salary'])
)
scatter.smooth(players2$EFFiciency, players2$Salary)
lines(lowess(x = players2$EFFiciency ,y= players2$Salary))
print (cor(players2$EFFiciency, players2$Salary))
```
The relationship between these more established players is in positive linear relationship. 


Part 6 
I think the homework is very difficult. It's hard especially in how to do condition filter in dataframe.
It's all hard.
I searched google for so many hours.
10 hours to finish it.
graphing.
