---
title: "warm_up1"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Use an unordered list (of bullets) to list the ingredients.

* eggs
* vegetables


Use another unordered list to list any "special" kitchen tools that are needed.

* chicken
* pork


Use an ordered list to list and describe all the steps of the recipe.

* wash vegetables
* boil egg
* cook chicken
* cook pork
* put together

If possible, look for an image online that you could insert to show the appearance of the meal (plate, drink, etc).

<https://www.google.com/search?q=egg+pork&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiUnrb2mbDWAhXmy1QKHceqAFgQ_AUICigB&biw=1440&bih=764#imgrc=Tkd2trzsQYLEnM:>

Also include a description of when to use the recipe?
anytime
Is there a special season of the year for it?
2018
Are there variations of the recipe? Using other ingredients?
No



What things were hard, even though you saw them in class?
What was easy(-ish) even though we haven't done it in class?
Was this the first time you were using markdown? If yes, how do you feel about it?
Yes, it's my first time use it. I'd say as a five year experienced programmer, markdown is terribly hard to use ^ ^.

If you have used markdown before, was there something new you learned while doing this assignment?
Did you need help to complete the assignment? If so, what kind of help? Who helped you?
How much time did it take to complete this HW?
I searched for a while
What was the most time consuming part?
I can't believe bullet points would need to seperate by a line to make it work. Awful.

