---
title: "hw03-Lai-Wei.RMD"
output: github_document
---



```{r}
library(readr)   
library(dplyr)   
library(ggplot2) 
```
TEAMS Ranking

```{r}
teams = read.csv("~/Desktop/stat133/stat133-hws-fall17/hw03/data/teams.csv")
arranged_teams = arrange(teams, desc(salary))
ggplot(teams, aes(reorder(team, salary), y = salary)) + geom_bar(stat = 'identity') + coord_flip() + geom_hline(yintercept= mean(teams$salary), color = 'red') + ggtitle('NBA Teams ranked by Salary') + xlab('Team') + ylab("Salary (in millions)")


ggplot(teams, aes(reorder(team, points), y = points)) + geom_bar(stat = 'identity') + coord_flip() + geom_hline(yintercept= mean(teams$points), color = 'red') + ggtitle('NBA Teams ranked by Total Points') + xlab('Team') + ylab("Total Points")


ggplot(teams, aes(reorder(team, efficiency), y = efficiency)) + geom_hline(yintercept= mean(teams$efficiency), color = 'red') + geom_bar(stat = 'identity') + coord_flip()+ ggtitle('NBA Teams ranked by Total Efficiency') + xlab('Team') + ylab("Total Efficiency")
#Concise descriptions of the rankings:
# Total points made are more important than efficiency because GSW beats CLE in final.

pca_prep = select(teams,points3,points2,free_throws,off_rebounds,def_rebounds, assists, steals, blocks, turnovers, fouls)
pca = prcomp(pca_prep, scale. = TRUE)
teams <- mutate(teams, pc1 = pca$x[ ,1],pc2 = pca$x[ ,2])
# Create a data frame witheigenvalues
eigns <- data.frame(
  eigenvalue = pca$sdev^2,
  prop = round((pca$sdev^2/sum(pca$sdev^2)), 4))
eigns = mutate(eigns, cumprop = cumsum(prop))
eigns
ggplot(data = teams,aes(x=pc1,y =pc2))+
  geom_point()+
  geom_label(aes(label = team)) + ggtitle('PCA plot(PC1 and PC2)')
  
pc1 = pca$x[ , 1]
s1 = 100*(pc1 - min(pc1))/(max(pc1) - min(pc1)) 
ggplot(teams, aes(reorder(team, pc1), y = s1)) + geom_bar(stat='identity') + coord_flip()  + ggtitle('NBA Teams ranked by scaled PC1') + xlab('Team') + ylab("First PC(scaled from 0 to 100)")

# description:
# from the graph, we can see Golden state warriors have the highest PC1. No wonder they're the champion.
```



```{r}
# Was this your first time working on a project with such file structure? If yes, how do
#you feel about it?
# no
# Was this your first time using relative paths? If yes, can you tell why they are important
#for reproducibility purposes?
# no, I'm cs major.
# because when sharing code with others, it can fit their laptop path
# Was this your first time using an R script? If yes, what do you think about just writing
#code? # no
# What things were hard, even though you saw them in class/lab?
# PCA is hard
# What was easy(-ish) even though we haven’t done it in class/lab?
# all hard
# Did anyone help you completing the assignment? If so, who?
# no
# How much time did it take to complete this HW?
# 4 hours
# What was the most time consuming part?
# PCA 

# Was there anything interesting?
# no
```
